### PR TITLE
Feat/docker laravel

### PR DESCRIPTION
**Pull request by griendt**
This is a full Laravel implementation of the current backend API. In essence it is a full re-write of the current specification.

Because Laravel itself generates a bunch of files and folders, this diff is pretty huge. The main directory of interest is `app/Http/Controllers`. This is where the API logic resides.

# Changes 
Some notable changes in the actual API include (but may not be limited to) the following.
## Returning other response codes than `200` and `400`
 - Most successful requests will return a `200 OK` response code and its content, as usual.
 - Validation errors will now return a `422 Unprocessable Entity` response code. The body of these responses take on the following form (default Laravel style):
```
{
  "message": "The given data was invalid.",
  "errors": {
    "other_player_id": [
      "The other player id field is required."
    ]
  }
}
```

 - When the player is unauthorized due to an invalid or expired token, a `401 Unauthorized` response is given (with empty body).
 - APIs that create a new resource may return a `201 Created` response code with no body, unless the old code generated a response body (such as event creation).
 - APIs that delete a resource may return a `204 No Content` response if the delete was successful, unless the old code generated a response body (such as event deletion).
 - When a resource could not be found (due to an id mismatch for example), a `404 Not Found` response is shown.

## Token generation
Token generation _should_ work the same as before in terms of client interaction, but the actual generation has changed slightly. Calling the `login` endpoint with the username/password combination should return a token using the same response format as before. The token is valid for one hour. After that, all calls that require a token will return `401 Unauthorized` until the client logs in again.

## Unique player name when registering
Aside from the e-mail address, player names now also have a unique constraint. This is to avoid issues when logging in with username and password only. In the future we could support duplicate player names by logging in via e-mail address instead.

## Message system
Previously, a message was sent from one player to one recipient. Now, there is a `message_group` table. Message groups are tied to a room (=game) and contain a list of players that are enlisted to that group.
 - To find out which message groups are available, the `get_room_data` response has been expanded with a key `message_groups`. This is a list of objects, which contain an `id` field. Perhaps we should remove this because Subterfuge does not support searching for chats and then joining them; the participant list is fixed upon creation. Feedback requested. However, if we remove this list, we should return message group id's in some other way (for example during creation; see below).
 - With the new endpoint `create_group` you can create a new message group. Mandatory parameters are the `room_id` and `participants[]` which is an array of player IDs. If successful, the resulting message group's data is returned in a `201 Created` response.

## Blocking other players
 - A block is now global: a player blocks another player entirely, and it applies independently of the room.
 - Previously it was impossible to fetch the list of blocked players! Now it is possible, via the new `get_blocks` request type. It will return a list of players you have blocked.
 - Note that messages are *not* filtered server-side! This is to ensure integrity in group chats which may contain blocked players. It will be up to the client to decide how to deal with these messages (hide them altogether, make them available with a button, etc.). The client should call the `get_blocks` endpoint to know which messages it should deal with.

## No separate tables for open and ongoing rooms
 - Rooms, whether they're in progress or not, are in essence the same type of resource. A field `started_at` (which may be null) indicates whether a room has started, and similarly, a field `closed_at` indicates whether a room has been closed.
 - As a result, various endpoints now have an extra check for whether rooms are open or not.

# Questions
I have made some assumptions or decided for certain things based on how it was implemented before. However I have placed a few question marks on existing specification and marked them with `TODO` or `FIXME`. Here is a quick rundown of questions:
 - When fetching an event, we validate whether the room has already started. It feels redundant, because a room that hasn't started has no events, and there's nothing stopping us from simply returning an empty list.
 - The `get_event` request has two possible filter parameters, `time` and `tick`. These two are confusing as they are in a sense synonymous. We should verify that the re-implementation is as intended. In addition, we should allow a combination of filters rather than just one filter argument.
 - The `get_event` response did not include a `"success": true` field, unlike other responses.
 - When creating a room, the client currently requires knowledge of the goal id. This is undesirable, as id's might change. Instead, we should use an identifier, such as `neptunium-200` or `outposts-15`.
 - When requesting a list of relevant rooms, I have decided to filter out closed rooms. This was not the case in the old codebase. However, in the old codebase, this meant that without a filter, *all* rooms could be returned from the database, which is undesirable.
 - Currently it is not possible for a player to leave a room when the game has already started. Should this remain the case? (Note that this is separate from resigning, which, actually, is still impossible.)
 - When a room is deleted, the response still gives that room's `id`. However this is undesirable as this implies that the id is still somehow useful when it isn't.
 - The `start_early` method is currently the only method that can start a game. Why is it called "early"?

# Issues
 - Considering the front-end currently requires precisely __one__ HTTP route (to the root) as a `POST`, the API is rather unconventional, which made adding the token middleware needlessly complex. In addition, having only one route will make it more difficult to track traffic when we go to production as well as make it harder to debug certain events. __Much__ better would be to have different routes for each type of resource (message, group, room, player, blocks) and set up a RESTful API following HTTP conventions (`GET` method to get info, `POST`/`PUT` to create/edit, `DELETE` to delete, etc.).

### CODE REVIEW

**Comment by QuinnBast** [comment]
When building with `php artisan migrate` I am encountering the following error:

```
php artisan migrate

   Illuminate\Database\QueryException

  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = sandbox and table_name = migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:670
    666|         // If an exception occurs when attempting to run a query, we'll format the error
    667|         // message to include the bindings with SQL, which will make this exception a
    668|         // lot more helpful to the developer instead of just the database's errors.
    669|         catch (Exception $e) {
  > 670|             throw new QueryException(
    671|                 $query, $this->prepareBindings($bindings), $e
    672|             );
    673|         }
    674|


      +39 vendor frames
  40  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by QuinnBast** [comment]
Update:
I had to change my `.env` file to include:
```
DB_HOST=db

MYSQL_HOST=db
```
and that resolved the previous errors. I also had to drop some tables that it kept from XAMPP for some reason. After dropping the tables I was able to confirm that it worked.

`new_room` - fails - I think its because of [this](https://github.com/laravel/ideas/issues/514)

### Question Answers

> When fetching an event, we validate whether the room has already started. It feels redundant, because a room that hasn't started has no events, and there's nothing stopping us from simply returning an empty list.

I agree, we don't think we need to validate that

> The get_event request has two possible filter parameters, time and tick. These two are confusing as they are in a sense synonymous. We should verify that the re-implementation is as intended. In addition, we should allow a combination of filters rather than just one filter argument.

I think we only need `tick`, as I will only be sending requests for "events after tick 67" for example. Agreed that multiple filters could be supported if required.

> The get_event response did not include a "success": true field, unlike other responses.

I noticed this as well, I think with status codes we can remove the `success: true` altogether if needed.

> When creating a room, the client currently requires knowledge of the goal id. This is undesirable, as id's might change. Instead, we should use an identifier, such as neptunium-200 or outposts-15.

I like this

> When requesting a list of relevant rooms, I have decided to filter out closed rooms. This was not the case in the old codebase. However, in the old codebase, this meant that without a filter, all rooms could be returned from the database, which is undesirable.

I agree, as long as we can add a filter that includes the closed rooms in the response

> Currently it is not possible for a player to leave a room when the game has already started. Should this remain the case? (Note that this is separate from resigning, which, actually, is still impossible.)

I think leaving a room after it has started should be the signal for "resigned".

> When a room is deleted, the response still gives that room's id. However this is undesirable as this implies that the id is still somehow useful when it isn't.

Agreed, we can remove the id

> The start_early method is currently the only method that can start a game. Why is it called "early"?

If a player joins a game and them joining the game makes the game hit the `max_players` it should auto start the game. The lobby host can choose to start the game early before the player limit is reached.

**Comment by griendt** [comment]
@QuinnBast I have made some changes reflecting your feedback. To summarize:
 - I changed the `.env.example` to use `db` as the host. I still plan to actually get rid of the duplicate envvars (one is required by the MySQL container, the other is used by Laravel) but I will make an issue for that and delve more deeply into it later as it is not a serious problem.
 - I removed the check on whether a room is ongoing before returning events.
 - I have left in both `tick and `time` as filters. No multi-filter support is added yet as we'd have to specify how that would work and how the endpoint would look like.
 - I stripped all `"success": true` fields.
 - I extended the `get_room_data` call with an optional parameter `return_closed_rooms` which, if set to `true`, will also return closed rooms.
 - I added a seeder (which you can run with `php artisan db:seed`, see the new README) which generates two goals (neptunium-200 and outposts-15).
 - I added an endpoint `get_goals` which returns all existing goals in the database.
 - When creating a new room, the field `goal` should now contain a goal identifier.
 - Leaving a room is now possible even after it has started, but doing so will increase the `resignations` counter for the player.
 - When a room has 0 players left, the room is no longer deleted instantly. I figured this was better for analytical and historical reasons (if we decide to purge old rooms later we could do so easily by querying for empty rooms).
 - When a room is full, it starts automatically (`started_at` gets filled with the current time).

I also added a CHANGELOG file summarizing all changes including the HTTP response codes that are currently in use.

**Comment by QuinnBast** [comment]
Tested all api routes in postman & confirmed all routes are working in the docker build. Everything looks great!

**Pull request merged**
